### ISSUE TITLE
Add support for custom fields

### ISSUE THREAD

**Issue by rburgst** [kolossal-io/gatsby-source-personio-xml#4]
currently the plugin only maps the default fields. However, personio allows you to add custom fields. So it would be cool to either auto-sense those or add a hook into `readJobsFromXml` so that those extra fields can be mapped by the plugin user.

**Comment by marijoo** [comment]
I like the idea of having a hook. Would you like to send a PR? Otherwise it could take a few weeks or months before I have some spare time.

**Comment by rburgst** [comment]
done

**Comment by rburgst** [comment]
In theory this could be done a bit easier if there wasnt the indirection in `readJobsFromXml` but I wanted to keep the changes to your original code as small as possible
